### ISSUE TITLE
http://www.36sprints.com/ 로 접근 안됨

### ISSUE THREAD

**Issue by jamie-chu** [36sprints/36sprints.github.io#1]
http://36sprints.com/ 로는 접근이 되는데,
http://www.36sprints.com/ 로는 접근이 안되네요.

**Comment by realgsong** [comment]
도메인 설정은 지금 막 끝내놔서 시간이 조금 걸릴 겁니다

**Comment by jamie-chu** [comment]
이제 접속 됩니다.
